### ISSUE TITLE
Are you this guy?

### ISSUE THREAD

**Issue by philiptzou** [xysmlx/xysmlx.github.com#1]
https://twitter.com/TheRickWilson/status/1326253313281716225

**Comment by xysmlx** [comment]
@philiptzou I am not this guy. This guy just has a same name. I also do not use Twitter.

**Comment by xysmlx** [comment]
Hi @philiptzou , I have been asked about the same question by some people today. So I am very curious about what happened.

**Comment by philiptzou** [comment]
@xysmlx Someone sent an email to Rick Wilson cursing his family get cancer. According to the tweet, the guy who sent the email has the same name as yours (Lingxiao Ma). You may want to clarify somehow if it's not you.

**Comment by philiptzou** [comment]
Btw, Rick Wilson is a republican who founded Lincoln Project and helped democrats defeated Donald Trump.

**Comment by xysmlx** [comment]
@philiptzou Thank you for the description. It seems that they may search the displayed name in the search engine like Google or Bing and find that my homepage has the same name. BTW, my gmail address is xysmlx#gmail.com and is not that email address. Thank you again for the description.
